name: GET NeoDB Cover Main Color

on:
  workflow_dispatch:
  repository_dispatch:
    types: [get-color-neodb]

jobs:
  douban:
    name: Get NeoDB Cover Color
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Backup Old Data
      run: |
        TIMESTAMP=$(date +%Y%m%d%H%M%S)
        BACKUP_FILE="data/backup/result_get_color_before_$TIMESTAMP.json"
        TARGET_FILE="data/result.json"
        
        if [[ -f "$TARGET_FILE" ]]; then
          cp -f $TARGET_FILE $BACKUP_FILE
          echo "Backed up old data to $BACKUP_FILE"
        else
          echo "There is no old data."
        fi


    #数据处理
    - name: Install axios
      run: npm install axios@1.8.4
    
    - name: Install color-thief
      run: npm i --save colorthief

    - name: Get Detail Data
      id: handel-json
      uses: actions/github-script@v7
      with:
        result-encoding: string
        script: |
          const axios = require('axios');
          const ColorThief = require('colorthief');
          const fs = require('fs');

          const targetFilePath = "data/movie.json";
          const resultFilePath = "data/result.json";

          let movieJson;
          try {
            const data = fs.readFileSync(targetFilePath, 'utf8');
            movieJson = JSON.parse(data);
          } catch (error) {
            console.error('Error reading JSON file:', error);
            core.setFailed('Failed to read JSON file');
          }


          let resultData = [];
          try {
            if (fs.existsSync(resultFilePath)) {
              resultData = fs.readFileSync(resultFilePath, 'utf8');
              resultData = JSON.parse(resultData).data;
              
              // 循环result.json
              for (const dataItem of resultData) {
                // 查找的属性
                const hasProperty = 'cover_color' in dataItem;

                if(!hasProperty) {
                  console.log(`${dataItem.title}中属性不存在, 现在添加`);
                  // 找到原数据
                  const postId = dataItem.post_id;
                  const targetItem = movieJson.data.find(item => item.post_id === postId);    
                  if(targetItem) {
                    try {
                      // 下载图片
                      const cover_url = targetItem.item.cover_image_url;
                      const imageResponse = await axios.get(cover_url, { responseType: 'arraybuffer' });

                      // 获取图片颜色
                      const color = await ColorThief.getColor(imageResponse.data);

                      // 修改属性
                      dataItem.cover_color = color;
                    
                    } catch (error) {
                      console.error(`Error when process image ${dataItem.title}:`, error);
                    }
                  }
                }
              }
            }
            //resultData.sort((a, b) => new Date(b.created_time) - new Date(a.created_time));

            fs.writeFileSync(resultFilePath, JSON.stringify({ data: resultData }));
            console.log(`Data saved to ${resultFilePath}`);
          } catch (readError) {
            console.error('Error reading result.json:', readError);
          }

    # 上传

    # 把修改后的数据提交到 GitHub 仓库
    - name: Git Add and Commit
      if: ${{ env.REMOTE_UUID != env.CURRENT_UUID }}
      uses: EndBug/add-and-commit@v9
      with:
        message: 'chore(data): update neodb data'
        committer_name: 'github-actions[bot]'
        committer_email: 'github-actions[bot]@users.noreply.github.com'
        add: |
          './data'
