name: Upload Halo

on:
  workflow_dispatch:
  repository_dispatch:
    types: [upload-data-to-halo]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Deploy to Halo
        run: |
          npx halo-static-pages-deploy-cli deploy -e ${{ secrets.HALO_UPLOAD_ENDPOINT }} -i ${{ secrets.HALO_UPLOAD_ID }} -t ${{ secrets.HALO_UPLOAD_TOKEN }} -f data/result.json